# Generated by Django 5.0.4 on 2024-04-18 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'card'), (2, 'upi'), (3, 'netbanking'), (4, 'wallet'), (5, 'cardless_emi')], default=None, null=True)),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Cancelled'), (3, 'Partially Paid'), (4, 'Paid'), (5, 'Failed'), (6, 'Refund')], default=1)),
                ('transaction_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('amount', models.FloatField()),
                ('vpa', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('bank', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('wallet', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('card_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('refund_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last4', models.CharField(max_length=4)),
                ('network', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=10)),
                ('issuer', models.CharField(max_length=10)),
                ('international', models.BooleanField()),
                ('emi', models.BooleanField()),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payment.payment')),
            ],
        ),
    ]
