# Generated by Django 5.0.4 on 2024-04-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_cardinformation_created_cardinformation_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinformation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
